name: Terraform
description: Runs Open Policy Agent against Terraform plans.
author: https://github.com/echoboomer
requirements:
  - docker
  - jq
configuration:
  properties:
    debug:
      type: boolean
    fail_step:
      type: boolean
    image:
      type: string
    policy_file:
      type: string
    resource_types_file:
      type: string
    resource_weights_file:
      type: string
    terraform_plan:
      type: string
    tests_dir:
      type: string
    version:
      type: string
  required:
    - terraform_plan
